# Local Appium configuration
automation.server.type=local
automation.server.url=http://127.0.0.1:4723
appium.platformName=Android
appium.automationName=UiAutomator2
appium.deviceName=Android Emulator
appium.app.path=drivers/Android.SauceLabs.Mobile.Sample.app.apk
appium.appPackage=com.swaglabsmobileapp
appium.appActivity=com.swaglabsmobileapp.SplashActivity
appium.noReset=false
appium.newCommandTimeout=180
appium.implicitWaitSeconds=10

# Remote Appium configuration example:
# automation.server.type=remote
# automation.server.url=https://username:accessKey@ondemand.us-west-1.saucelabs.com:443/wd/hub
# appium.platformName=Android
# appium.automationName=UiAutomator2
# appium.deviceName=Google Pixel 7
# appium.app.path=drivers/Android.SauceLabs.Mobile.Sample.app.apk
